data:
  processed_dir: "data/processed"
  
  raw:
    target: 
      name: "music"
      path: "data/raw/Digital_Music.jsonl"

    sources: 
      - name: "movies_and_tv"
        path: "data/raw/Movies_and_TV.jsonl"
      # - name: "appliances"
      #   path: "data/raw/Appliances.jsonl"
      # - name: "movies"
        # path: "data/raw/Movies.jsonl"

model:
  type: "lightgcn"   # gat | sage | gcn | lightgcn
  hidden_channels: 32 # hidden embedding size, increase if underfits, decrease if overfits
  out_channels: 32 # final embedding size
  num_layers: 2 # 2 hop neighborhood
  heads: 2   # number of attention heads
  dropout: 0.1    # dropout rate
  edge_dim: 4

training:
  loss_type: "bpr_softplus"   # bpr_sigmoid | bpr_softplus | hinge
  num_epochs: 5
  batch_size: 512
  val_batch_size: 1024
  learning_rate: 0.001
  weight_decay: 0.0
  reg_lambda: 0.0001    # L2 regularization coefficient
  device: "auto"              # auto | cpu | cuda

logging:
  level: "INFO"